# **Analisis Sentimen Masyarakat terhadap Program Makan Bergizi Gratis Berdasarkan Komentar YouTube**

#Instal Library

In [ ]:
!pip install youtube-comment-downloader

Collecting youtube-comment-downloader
  Downloading youtube_comment_downloader-0.1.78-py3-none-any.whl.metadata (2.9 kB)
Collecting dateparser (from youtube-comment-downloader)
  Downloading dateparser-1.4.1-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from youtube-comment-downloader) (2.32.4)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from dateparser->youtube-comment-downloader) (2.9.0.post0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser->youtube-comment-downloader) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser->youtube-comment-downloader) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser->youtube-comment-downloader) (5.4.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-comment-downloader) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-comment-downloader) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-comment-downloader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-comment-downloader) (2026.6.17)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7.0->dateparser->youtube-comment-downloader) (1.17.0)
Downloading youtube_comment_downloader-0.1.78-py3-none-any.whl (8.3 kB)
Downloading dateparser-1.4.1-py3-none-any.whl (300 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.5/300.5 kB 2.5 MB/s eta 0:00:00
Installing collected packages: dateparser, youtube-comment-downloader
Successfully installed dateparser-1.4.1 youtube-comment-downloader-0.1.78

#Import Library

In [ ]:
import pandas as pd
from youtube_comment_downloader import YoutubeCommentDownloader
pd.set_option('display.max_colwidth', None)

#Sracping Comments Youtube

In [22]:
downloader = YoutubeCommentDownloader()

# Daftar URL YouTube
urls = [
    "https://www.youtube.com/watch?v=0BRFlBVWH3c",
    "https://www.youtube.com/watch?v=a2WXt0aW76g"
]

all_comments = []

for url in urls:
    print(f"Mengambil komentar dari: {url}")

    count = 0
    try:
        for comment in downloader.get_comments_from_url(url):
            comment["video_url"] = url  # Menambahkan informasi asal video
            all_comments.append(comment)

            count += 1
            if count == 5000:      # Maksimal 5000 komentar per video
                break

    except Exception as e:
        print(f"Gagal mengambil komentar dari {url}")
        print(e)

# Mengubah menjadi DataFrame
df_youtube = pd.DataFrame(all_comments)

df_youtube.head()

Mengambil komentar dari: https://www.youtube.com/watch?v=0BRFlBVWH3c
Mengambil komentar dari: https://www.youtube.com/watch?v=a2WXt0aW76g

,cid,text,time,author,channel,votes,replies,photo,heart,reply,time_parsed,video_url,paid
0,UgxokclGBDxsTOqz-XR4AaABAg,Tiba masanya Sumatra berpisah dr Indonesia kerna gagal mentakbir negara,3 小時前,@deandin3068,UCQvSdkDKNfjU3Eqo7p2llZw,0,,https://yt3.ggpht.com/ytc/AIdro_lxy2NXNyBgDZbw-Y5Y5YYnp6S8rimrC2OqDkv2F-Qrj0g=s88-c-k-c0x00ffffff-no-rj,False,False,1.783467e+09,https://www.youtube.com/watch?v=0BRFlBVWH3c,NaN
1,UgznI1mbhj8G8Mkmo4t4AaABAg,"11:16 beliau mengutamakan muridnya menjadi baik dahulu. \n\nRespect pak, jasa mu tak tergganti ❤",3 天前,@KuchoengNyudae,UCeMKvFL929jDmZdQsohJWVw,0,,https://yt3.ggpht.com/ytc/AIdro_m-Whn0Wjn4D0JTJ5rHJka27FaY5osfTymbSE6CCkgHNVQ=s88-c-k-c0x00ffffff-no-rj,False,False,1.783219e+09,https://www.youtube.com/watch?v=0BRFlBVWH3c,NaN
2,UgysLjO9gDxSdSGsPAN4AaABAg,pasti ada pihak 3 yg memberikan racun utk menjatukan prabowo,4 天前,@Ammarbm-rx4zw,UCBzqS8B0Wznjexn72uLKDbg,0,,https://yt3.ggpht.com/ytc/AIdro_meYAh6NPkc3qZ9RQbztfozX2jknUqc69hcasQTLZa7CCWY6MHmzRI1I6I59gYFhEiQXA=s88-c-k-c0x00ffffff-no-rj,False,False,1.783133e+09,https://www.youtube.com/watch?v=0BRFlBVWH3c,NaN
3,Ugxmn111o_y5ASKsoEt4AaABAg,Ngeriii ya pengajar digajih sedikit.pegawai MBG dikasih motor gajih gdee,6 天前,@SuhaeliParid-sq8wn,UCpPr-5-Esm5OGtzajFQ67Lg,0,,https://yt3.ggpht.com/ytc/AIdro_nn2r27xgt-QLsA4NOafS588bIhGJEP80r8XEC4pJEMwtmsmIosL5hG9gzQ2AyEbG8G0A=s88-c-k-c0x00ffffff-no-rj,False,False,1.782960e+09,https://www.youtube.com/watch?v=0BRFlBVWH3c,NaN
4,UgzMImGEf8PsgIY2OFx4AaABAg,MBG Mas Bwahlil Genteng,8 天前,@xiaoling6867,UCMCuwwCIBgLJymsn9jCd6fw,0,,https://yt3.ggpht.com/ytc/AIdro_nW6zUsPmvIJJvJqsR2r6eI2FMrl2lRmr1ATIPqoXh67LJfNLScA4BjvVGG7MSCwhIIsQ=s88-c-k-c0x00ffffff-no-rj,False,False,1.782787e+09,https://www.youtube.com/watch?v=0BRFlBVWH3c,NaN

In [23]:
#melihat ada berapa banyak data
df_youtube.shape

(6552, 13)

#Data Cleaning Sementara

##Ubah Tipe Data

In [24]:
#mengubah data pada kolom Time
df_youtube['time'] = pd.to_datetime(
    df_youtube['time_parsed'], unit='s'
).dt.strftime('%d-%m-%Y %H:%M:%S')

In [25]:
df_youtube.head()

,cid,text,time,author,channel,votes,replies,photo,heart,reply,time_parsed,video_url,paid
0,UgxokclGBDxsTOqz-XR4AaABAg,Tiba masanya Sumatra berpisah dr Indonesia kerna gagal mentakbir negara,07-07-2026 23:35:47,@deandin3068,UCQvSdkDKNfjU3Eqo7p2llZw,0,,https://yt3.ggpht.com/ytc/AIdro_lxy2NXNyBgDZbw-Y5Y5YYnp6S8rimrC2OqDkv2F-Qrj0g=s88-c-k-c0x00ffffff-no-rj,False,False,1.783467e+09,https://www.youtube.com/watch?v=0BRFlBVWH3c,NaN
1,UgznI1mbhj8G8Mkmo4t4AaABAg,"11:16 beliau mengutamakan muridnya menjadi baik dahulu. \n\nRespect pak, jasa mu tak tergganti ❤",05-07-2026 02:35:47,@KuchoengNyudae,UCeMKvFL929jDmZdQsohJWVw,0,,https://yt3.ggpht.com/ytc/AIdro_m-Whn0Wjn4D0JTJ5rHJka27FaY5osfTymbSE6CCkgHNVQ=s88-c-k-c0x00ffffff-no-rj,False,False,1.783219e+09,https://www.youtube.com/watch?v=0BRFlBVWH3c,NaN
2,UgysLjO9gDxSdSGsPAN4AaABAg,pasti ada pihak 3 yg memberikan racun utk menjatukan prabowo,04-07-2026 02:35:47,@Ammarbm-rx4zw,UCBzqS8B0Wznjexn72uLKDbg,0,,https://yt3.ggpht.com/ytc/AIdro_meYAh6NPkc3qZ9RQbztfozX2jknUqc69hcasQTLZa7CCWY6MHmzRI1I6I59gYFhEiQXA=s88-c-k-c0x00ffffff-no-rj,False,False,1.783133e+09,https://www.youtube.com/watch?v=0BRFlBVWH3c,NaN
3,Ugxmn111o_y5ASKsoEt4AaABAg,Ngeriii ya pengajar digajih sedikit.pegawai MBG dikasih motor gajih gdee,02-07-2026 02:35:47,@SuhaeliParid-sq8wn,UCpPr-5-Esm5OGtzajFQ67Lg,0,,https://yt3.ggpht.com/ytc/AIdro_nn2r27xgt-QLsA4NOafS588bIhGJEP80r8XEC4pJEMwtmsmIosL5hG9gzQ2AyEbG8G0A=s88-c-k-c0x00ffffff-no-rj,False,False,1.782960e+09,https://www.youtube.com/watch?v=0BRFlBVWH3c,NaN
4,UgzMImGEf8PsgIY2OFx4AaABAg,MBG Mas Bwahlil Genteng,30-06-2026 02:35:47,@xiaoling6867,UCMCuwwCIBgLJymsn9jCd6fw,0,,https://yt3.ggpht.com/ytc/AIdro_nW6zUsPmvIJJvJqsR2r6eI2FMrl2lRmr1ATIPqoXh67LJfNLScA4BjvVGG7MSCwhIIsQ=s88-c-k-c0x00ffffff-no-rj,False,False,1.782787e+09,https://www.youtube.com/watch?v=0BRFlBVWH3c,NaN

#Download Dataset

In [32]:
df_youtube.to_csv('mbgscrapping.csv', index=False)